# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - release/*


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      
    - name: Set Go environment Install all the dependencies
      run: |
          whoami
          ls
          echo $PATH
          cd $GITHUB_WORKSPACE
          go version
          go mod init sample
          go mod tidy
          go get honnef.co/go/tools/cmd/staticcheck
          go install honnef.co/go/tools/cmd/staticcheck
          export GOPATH="$HOME/go"
          export PATH="$GOPATH/bin:$PATH"
          staticcheck .
          go vet .
          go test -v
      shell: bash 
