# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Setup Go
      - uses: actions/checkout@v3

    - name: Set Go environment Install all the dependencies
      run: |
          whoami
          echo $PATH
          cd $GITHUB_WORKSPACE
          go version
          go mod init sample
          go mod tidy
          go get -u golang.org/x/lint/golint
          
          go vet .
          go lint .
          go test -v
      shell: bash 
